lib/fish_pot_web/router.ex
defmodule FishPotWeb.Router do
  use FishPotWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
#    plug FishPotWeb.Auth, repo: FishPotWeb.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FishPotWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", AuthController, :login
    get "/auth", AuthController, :authenticate
    get "/logout", AuthController, :logout

    get "/upload", UploadController, :index
    post "/upload", UploadController, :create

    resources "/users", UserController
    resources "/workers", WorkerController
    resources "/companies", CompanyController
    resources "/projects", ProjectController
    resources "/jobs", JobController

  end

  # Other scopes may use custom stacks.
  # scope "/api", FishPotWeb do
  #   pipe_through :api
  # end
end

lib/fish_pot_web/templates/page/index.html.eex
<h2>Fish Pot Project</h2>
<div class="row">
    <div class="col">COL A</div>
    <div class="col">COL B</div>
    <div class="col">COL C</div>
    <div class="col">COL D</div>
</div>
<div class="row">
    <div class="col">COL A</div>
    <div class="col">COL B</div>
</div>
<div class="row">
    <div class="col">COL A</div>
    <div class="col">COL B</div>
    <div class="col">COL C</div>
</div>
<div class="row">
    <div class="col-sm-5">COL A</div>
    <div class="col-sm-3">COL B</div>
    <div class="col-sm-4">COL C</div>
</div>

<div class="row">
    <div class="col">
        <%= link "User", to: user_path(@conn, :index) %>
    </div>
    <div class="col">
        <%= link "Worker", to: worker_path(@conn, :index) %>
    </div>
    <div class="col">
        <%= link "Company", to: company_path(@conn, :index) %>
    </div>
    <div class="col">
        <%= link "Project", to: project_path(@conn, :index) %>
    </div>
    <div class="col">
        <%= link "Job", to: job_path(@conn, :index) %>
    </div>
    <div class="col">

<style>
    div{
        padding: 5px 10px;
        border: 1px solid lightgrey;
    }
</style>